Reformat long orphan commit message
archlinuxcn/misc_scripts pull request #14
Opened 2019-05-20 12:36 UTC by ShadowRZ

如题。

不然有时候提交信息过于长然后就……
（比如说 https://github.com/archlinuxcn/repo/commit/dedbaecbc010aabfb94e4d9b94fb1f1d7f89d285 ）

PS: 手机上提交果然…Emmmm

2019-05-20 13:15 UTC, lilydjwg requested changes

2019-05-20 13:15 UTC, lilydjwg commented on issuebot
> +          msg = f'Removing {len(packages)} due to being orphaned for a long time.\n\nAffected packages:\n{"\n".join([f"- {x}" for x in packages])}\n\ncloses #{issue.number}'
行太长。`.join` 可以接受 generator，所以也不需要长成列表。

2019-05-20 22:08 UTC, ShadowRZ commented on issuebot
> +          msg = f'Removing {len(packages)} due to being orphaned for a long time.\n\nAffected packages:\n{"\n".join([f"- {x}" for x in packages])}\n\ncloses #{issue.number}'
噗，[Generator expressions](https://docs.python.org/3/tutorial/classes.html#generator-expressions) 只与我的代码差了方括号与括号的区别……

我用的语法是 https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions

2019-05-21 06:33 UTC, ShadowRZ commented on issuebot
> +          msg = f'Removing {len(packages)} due to being orphaned for a long time.\n\nAffected packages:\n{"\n".join([f"- {x}" for x in packages])}\n\ncloses #{issue.number}'
Done: https://github.com/archlinuxcn/misc_scripts/pull/14/commits/6459ce8defe7ca99b606620d4278b948dadd5f0f

2019-05-21 08:01 UTC, lilydjwg requested changes

2019-05-21 08:01 UTC, lilydjwg commented on issuebot
> +          'closes #{issue.number}'
字符串这么放在多行是要加括号的。而且每一个需要的都要加 f 前缀。不如用 ''' 方便。

2019-05-21 08:13 UTC, ShadowRZ commented on issuebot
> +          'closes #{issue.number}'
Done: https://github.com/archlinuxcn/misc_scripts/pull/14/commits/8af3ebf360f292bf025a33d5a4912e67a64e611f

2019-05-21 08:14 UTC, ShadowRZ commented
我希望这一个提交不要把 lilac 搞砸了

2019-05-21 08:19 UTC, ShadowRZ commented
PS: 最好最后压缩成一个提交，因为我提交时各种错字

2019-05-21 10:23 UTC, merged

2019-05-21 10:28 UTC, lilydjwg commented
应该没问题吧。有问题也影响不到 lilac 打包的。