Make who_depends_this_lib much faster
archlinuxcn/misc_scripts pull request #15
Opened 2019-10-25 03:07 UTC by yan12125

An example run:
```
$ time env PYTHONPATH=$HOME/tmp/winterpy/pylib python who_depends_this_lib /data/repo/x86_64/archlinuxcn.files libproto protobuf >&| ~/tmp/output
env PYTHONPATH=$HOME/tmp/winterpy/pylib python who_depends_this_lib  libproto  72.35s user 6.32s system 99% cpu 1:19.26 total
```

2019-10-25 07:42 UTC, lilydjwg requested changes

2019-10-25 07:42 UTC, lilydjwg commented on who_depends_this_lib
> +    threshold = 10
You can use `itertools.islice`.

2019-10-25 07:42 UTC, lilydjwg commented on who_depends_this_lib
> +          if line.startswith('installed = ') and dep_pkgname in line:
`dep_pkgname in line` doesn't split on spaces, e.g. `'python' in 'python2'` will return True.

2019-10-25 07:42 UTC, lilydjwg commented on who_depends_this_lib
> +          threshold, pkg))
Don't format the string yourself with `%`. `logging` will format it when outputing (and the orignal format message will be available for the logging system, e.g. Sentry will group them together even when the arguments are different).

2019-10-26 15:05 UTC, yan12125 commented
Thank you for the review. I added a commit to address those comments. Here is an issue: it turns out that a few packages are built using pacman < 5.1, so that there is no valid `.BUILDINFO`. I'd like to propose them to be rebuilt and thus this PR can be simplified.

2019-10-26 17:17 UTC, lilydjwg commented
Yes, we can rebuild those packages. Can you get a list of them?

2019-10-27 00:42 UTC, yan12125 commented
Here is the package list:

<details>
<summary>pkgs.txt</summary>

```
abootimg-git
alert-after
android-sdk
angrysearch
apache-tools
archey-git
aurvote
awesome34
bilidan-git
brother-hl2140
byzanz-git
ccal
cdate
cla
cld2-git
clup
coccinelle
codecs64
cuda_memtest
dbus-cpp
deadbeef-plugin-infobar-ng-gtk2-hg
deadbeef-plugin-infobar-ng-gtk3-hg
drive
fbcat
figlet-fonts
flow-pomodoro
fontweak
freerapid
ghq
glib
gnome-search-tool-no-nautilus
google-earth
govendor
hal-flash-git
hpoj
hydroxygen-iconset
i3-gnome-git
img2sdat-git
ipad_charge
ispin
jave
julia-pkg-scripts
kega-fusion
key-mon
kjieba
lib32-gdbm
lib32-oxygen-gtk2
lib32-qt4
lib32-tk
libbonoboui
libgnome
libgnome-data
libgnomeui
libnatspec
loc
lua51-doc
minecraft
mingw-w64-zlib
moeditor-bin
monogame-git
mpdscribble
nant
newrelic-php53
newrelic-sysmond
nifskope-git
notify-desktop-git
ntpdate
obkey-git
openbrf
openlibm-git-debug
openvdb3
openvpn-obfs
pacnew-auto-git
paman
pavumeter
pcsxr-git
php53-apc
php53-mongo
pidgin-wechat-git
pkgtools
plasma5-applets-active-window-control-git
pnmixer-gtk3
python2-bjoern
python2-newrelic
qrsctl
qtadb
rawstudio-git
rsync-noatime
ruby2.2
ruby-hiera
screenkey
sfml1.6
shadowvpn
shine
silentcast
simage
simage-debug
simple-mtpfs
slurm
sniproxy
spin
sublime-text-imfix
tchrome
toilet
uksmtools
unzip-natspec
vicare-scheme-git
w3watch
wallch
xavs
xfce4-mpc-plugin-update
xfce4-soundmenu-plugin
xflux
xinput_calibrator
yaourt
zpaq
```

</details>

And raw output using https://github.com/yan12125/misc_scripts/commit/affb9afb52de8eb6daee7b3e98bfb00facb3307c:

<details>
<summary>buildinfo-issue.txt</summary>

```
[W 10-27 08:13:05.603 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-2 found in /data/repo/x86_64/abootimg-git-0.6.r6.g1ebeb39-1-x86_64.pkg.tar.xz
[W 10-27 08:13:05.615 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/alert-after-1.4.3-1-x86_64.pkg.tar.xz
[W 10-27 08:13:05.867 who_depends_this_lib:83] Old .BUILDINFO format - entry installed =  found in /data/repo/x86_64/android-sdk-26.1.1-1-x86_64.pkg.tar.xz
[W 10-27 08:13:05.882 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/angrysearch-1.0.1-1-any.pkg.tar.xz
[W 10-27 08:13:05.887 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-3 found in /data/repo/x86_64/apache-tools-2.4.25-1-x86_64.pkg.tar.xz
[W 10-27 08:13:05.896 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/archey-git-r146.b74e40br146.b74e40b-1-any.pkg.tar.xz
[W 10-27 08:13:05.926 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-2 found in /data/repo/x86_64/aurvote-1.9-3-any.pkg.tar.xz
[W 10-27 08:13:05.930 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/awesome34-3.4.15-2-x86_64.pkg.tar.xz
[W 10-27 08:13:05.968 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-3 found in /data/repo/x86_64/bilidan-git-20170704-1-any.pkg.tar.xz
[W 10-27 08:13:05.986 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = a52dec-0.7.4-8 found in /data/repo/x86_64/brother-hl2140-2.0.2_1-4-x86_64.pkg.tar.xz
[W 10-27 08:13:05.995 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-2 found in /data/repo/x86_64/byzanz-git-0.2.1.126.g81235d2-1-x86_64.pkg.tar.xz
[W 10-27 08:13:06.000 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-2 found in /data/repo/x86_64/ccal-2.5.3-2-x86_64.pkg.tar.xz
[W 10-27 08:13:06.005 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/cdate-1.0.5-1-x86_64.pkg.tar.xz
[W 10-27 08:13:06.021 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = a52dec-0.7.4-8 found in /data/repo/x86_64/cla-1.0-4-any.pkg.tar.xz
[W 10-27 08:13:06.029 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-3 found in /data/repo/x86_64/cld2-git-20150820-3-x86_64.pkg.tar.xz
[W 10-27 08:13:06.048 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = a52dec-0.7.4-8 found in /data/repo/x86_64/clup-1.1-4-any.pkg.tar.xz
[W 10-27 08:13:06.055 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/coccinelle-1.0.6-2-x86_64.pkg.tar.xz
[W 10-27 08:13:06.076 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/codecs64-20071007-1-x86_64.pkg.tar.xz
[W 10-27 08:13:06.200 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-3 found in /data/repo/x86_64/cuda_memtest-1.2.3-3-x86_64.pkg.tar.xz
[W 10-27 08:13:06.211 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/dbus-cpp-5.0.0-4-x86_64.pkg.tar.xz
[W 10-27 08:13:06.268 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/deadbeef-plugin-infobar-ng-gtk2-hg-189-1-x86_64.pkg.tar.xz
[W 10-27 08:13:06.270 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/deadbeef-plugin-infobar-ng-gtk3-hg-189-1-x86_64.pkg.tar.xz
[W 10-27 08:13:06.318 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-3 found in /data/repo/x86_64/drive-0.3.9.1-2-x86_64.pkg.tar.xz
[W 10-27 08:13:06.377 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/fbcat-0.5.1-1-x86_64.pkg.tar.xz
[W 10-27 08:13:06.423 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/figlet-fonts-1.0-3-any.pkg.tar.xz
[W 10-27 08:13:06.621 who_depends_this_lib:83] Old .BUILDINFO format - entry installed =  found in /data/repo/x86_64/flow-pomodoro-1.2.0-4-x86_64.pkg.tar.xz
[W 10-27 08:13:06.637 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-3 found in /data/repo/x86_64/fontweak-1.3.1-2-any.pkg.tar.xz
[W 10-27 08:13:06.656 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/freerapid-0.9u4-1-any.pkg.tar.xz
[W 10-27 08:13:09.689 who_depends_this_lib:83] Old .BUILDINFO format - entry installed =  found in /data/repo/x86_64/ghq-0.8.0-1-x86_64.pkg.tar.xz
[W 10-27 08:13:09.716 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = a52dec-0.7.4-8 found in /data/repo/x86_64/glib-1.2.10-14-x86_64.pkg.tar.xz
[W 10-27 08:13:09.729 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = a52dec-0.7.4-8 found in /data/repo/x86_64/gnome-search-tool-no-nautilus-3.6.0-4-x86_64.pkg.tar.xz
[W 10-27 08:13:09.764 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-3 found in /data/repo/x86_64/google-earth-7.1.8.3036-1-x86_64.pkg.tar.xz
[W 10-27 08:13:09.768 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/govendor-1.0.9-1-x86_64.pkg.tar.xz
[W 10-27 08:13:09.808 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = a52dec-0.7.4-8 found in /data/repo/x86_64/hal-flash-git-0.3.3-1-x86_64.pkg.tar.xz
[W 10-27 08:13:09.839 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-2 found in /data/repo/x86_64/hpoj-0.91-21-x86_64.pkg.tar.xz
[W 10-27 08:13:09.861 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/hydroxygen-iconset-20090119-2-x86_64.pkg.tar.xz
[W 10-27 08:13:09.872 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/i3-gnome-git-5.2.r4.g859779d-1-any.pkg.tar.xz
[W 10-27 08:13:09.888 who_depends_this_lib:83] Old .BUILDINFO format - entry installed = acl-2.2.52-4 found in /data/repo/x86_64/img2sdat-git-r28.a4fdf7c-1-x86_64.pkg.tar.xz
[W 10-27 08:13:09.912 who_depends_this_lib:92] Cannot find .BUILDINFO in first 10 entries of /data/repo/x86_64/ipad_charge-1.1-4-x86_64.pkg.tar.xz
[W 10-27 08 [...]

2019-10-27 12:30 UTC, lilydjwg commented
那个文本是用这样的 Python 脚本生成的：

<details>
<summary>script issue1073</summary>

```py
#!/usr/bin/python3

from pathlib import Path
import logging
from collections import defaultdict

from lilac2 import lilacpy

logger = logging.getLogger(__name__)

def main():
  repodir = Path('/ldata/src/archgitrepo/archlinuxcn')
  mods, _ = lilacpy.load_all(repodir)
  r = defaultdict(list)

  for name, m in mods.items():
    if getattr(m, 'build_prefix', '').startswith(('archlinuxcn-', 'multilib-archlinuxcn')):
      for x in m.maintainers:
        r[x['github']].append(name)

  for who, pkgs in sorted(r.items()):
    print(f'@{who}:')
    for pkg in pkgs:
      print('* [ ]', pkg)
    print()

if __name__ == '__main__':
  from nicelogger import enable_pretty_logging
  enable_pretty_logging('DEBUG')
  main()
```
</details>

2019-10-27 12:40 UTC, lilydjwg commented
It looks OK, please open an issue to move things forward :+1:

2019-10-28 03:42 UTC, yan12125 commented
Looks like `lilacpy.load_all(repodir)` skips packages with `managed: false`. I read lilac.yaml files directly and created https://github.com/archlinuxcn/repo/issues/1351.

2019-10-28 07:18 UTC, lilydjwg commented
I changed `load_all` and added a new `load_managed`.

2019-10-28 07:39 UTC, yan12125 commented
Thanks!

2019-10-28 16:20 UTC, yan12125 commented
Squashed and force-pushed. I consider this ready for another review if you want to merge it before https://github.com/archlinuxcn/repo/issues/1351 is done and you are fine with nasty `.BUILDINFO` handling codes.

2019-10-29 07:07 UTC, merged

2019-10-29 07:07 UTC, lilydjwg commented
Thanks!